INSERT INTO planes (
  user_id,
  title,
  description,
  condition,
  year,
  make,
  model,
  planes_class,
  airframe_hours,
  engine_hours,
  plane_photos_id,
  price,
  active,
  sold,
  featured,
  date_posted
  ) VALUES (
    1,
    '1956 Beechcraft BONANZA',
    'One of the nicest G35 Bonanza''s on the marked. VREF value is WELL over 100,000. The book says 184 MPH but with the speed mods and depending on temperature, I''ve actualy seen 190 TAS at 7,500 ft. The service ceiling is 19,000 ft. which is about 2,000 ft. higher than the newer Bonanza''s. Comes with pilot and co-pilot David Clark headsets, tow bar and a 4 place portable oxygen system. Always hangared but also comes with a like new custom made cover for overnight trips.',
    'Used',
    1956,
    'Beechcraft',
    'BONANZA',
    'Single Engine Prop',
    4776,
    636,
    1,
    88000,
    TRUE,
    FALSE,
    FALSE,
    '2021-01-15 14:30'),
(   1,
    '1982 Mooney M20K 231',
    'This Mooney has been maintained in North Dakota by Bismarck and Mandan Aero Center. Annuals have been always current. There are only 26 hours SMOH and a new Hartzell prop with the same number of hours. Major overhaul was completed at Bismarck Aero Center. The annual was completed in August, 2023. Engine and Aircraft logbooks are available at Mandan Aero Center for inspection. Plane has always been hangared and is currently at Mandan Airport.',
    'Used',
    1982,
    'Mooney',
    'M20K 231',
    'Single Engine Prop',
    3209,
    536,
    2,
    139900,
    FALSE,
    TRUE,
    FALSE,
    '2021-02-15 13:30'),
(   1,
  '1973 PIPER ARROW, Single Engine Piston',
  '1973 Piper Arrow For Sale.',
  'Used',
  1973,
  'Piper',
  'ARROW',
  'Single Engine Prop',
  5272,
  312,
  3,
  115000,
  FALSE,
  FALSE,
  FALSE,
  '2021-03-22 14:30'),
( 1,
  '1975 Beechcraft F33A',
  '1975 BEECHCRAFT F33A BONANZA, Single Engine Piston, LVAS is proud to bring this low time and Turbo Normalized Bonanza. With this TN IO-520, solid IFR panel (with standby vac/alt), and tip tanks the next owner will have a great XC platform.Fresh annual in November 2023! This bird is ready to fly to its new home!',
  'Used',
  1975,
  'Beechcraft',
  'F33A BONANZA',
  'Single Engine Prop',
  2896,
  420,
  4,
  92000,
  'TRUE',
  'TRUE',
  'FALSE',
  '2021-03-22 14:30'),
( 1,
  '1966 Mooney M20E',
  'This Mooney has been maintained in North Dakota by Bismarck and Mandan Aero Center. Annuals have been always current. There are only 26 hours SMOH and a new Hartzell prop with the same number of hours. Major overhaul was completed at Bismarck Aero Center. The annual was completed in August, 2023. Engine and Aircraft logbooks are available at Mandan Aero Center for inspection. Plane has always been hangared and is currently at Mandan Airport.',
  'Used',
  1966,
  'Mooney',
  'M20E',
  'Single Engine Prop',
  5647,
  2600,
  5,
  99500,
  'FALSE',
  'TRUE',
  'FALSE',
  '2021-03-22 14:30'),
( 1,
  '2006 Cirrus SR22 GTS',
  'The low 1224 always hangered and pampered beauty must be see to believe. Full Logs and NO DAMAGE HISTORY! All the bells and whistles, AC, Glass cockpit, XM Satelliet weather and music and much more. This is the easiest high performance airplane to fly and land. Includes gas powered tug and GPU/Charger unit.',
  'Used',
  2006,
  'Cirrus',
  'SR22 GTS',
  'Single Engine Prop',
  1604,
  1604,
  6,
  350000,
  'FALSE',
  'TRUE',
  'FALSE',
  '2022-05-28 22:30'),
( 1,
  '1999 Cessna T-206H',
  '1999 Cessna T206H With An Upgraded Rolls Royce M250 (420hp) Turbine Engine. This Is A Beautiful Law Enforcement Agency Fleet Maintained and Hangered Aircraft With An Excellent Airframe and No Damage History Located In Tucson, Arizona @ TUS. Additional Features Include Flint Arrow Tip Tanks, Dual Garmin GNS430W GPS/NAV/COMM, Garmin G500 Dual Screen Flight Display, Soloy LED Taxi/Landing Lights, Prop De-Ice and Heated Inlet, Air Conditioning, Soloy Observation Window and a Hartzell Prop, All Of Which Makes This A Very Comfortable and Capable Cross-Country Machine. Excellent Airframe and No Damage History.',
  'Used',
  1999,
  'Cessna',
  'T-206H',
  'Single Engine Prop',
  6731,
  5576,
  7,
  650000,
  'TRUE',
  'FALSE',
  'TRUE',
  '2021-01-15 14:30'),
( 1,
  '1978 Cessna 172',
  'Out of Annual Last Annual 04/07/2022. Located at FFZ - This Cessna has had a very strong maintenance history (including complete logs) until the time it was placed into retirement due to the agency no longer utilizing fixed wing aircraft. Aircraft is hangered at Falcon Field in Mesa AZ and is a great opportunity to get into a very well maintained aircraft at a very economical price. Interior 4/10 exterior 5/10. Law Enforcement Fleet Maintained & City of Mesa, AZ Fleet Asset.',
  'Used',
  1978,
  'Cessna',
  '172',
  'Single Engine Prop',
  9382,
  2774,
  8,
  80000,
  'TRUE',
  'FALSE',
  'TRUE',
  '2021-01-15 14:30'),
( 1,
	'1965 Cessna 182H SKYLANE',
  '1965 CESSNA 182H SKYLANE, Single Engine Piston, 1965 Cessna 182H Skylane, N629CM, Lovingly Restored, Recent Paint, Prop and Engine Overhaul, Garmin G5''s GNX 375 WAAS Avionics.',
  'Used',
  1965,
  'Cessna',
  '182H SKYLANE',
  'Single Engine Prop',
  5049,
  3210,
  9,
  180000,
  'TRUE',
  'FALSE',
  'FALSE',
  '2022-05-28 22:30'),
( 1,
  '1972 Piper',
  '1972 PIPER CHEROKEE 235, Single Engine Piston, A "one of a kind" perfect Cherokee 235 for great cross country experiences for you and your family with a fantastic (over 1400 lb.) useful load.',
  'Used',
  1972,
  'Piper',
  'CHEROKEE 235',
  'Single Engine Prop',
  4720,
  3000,
  10,
  109900,
  'TRUE',
  'FALSE',
  'FALSE',
  '2021-01-15 14:30');







