DROP TABLE IF EXISTS planes CASCADE;
CREATE TABLE planes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  condition VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  planes_class VARCHAR(255) NOT NULL,
  airframe_hours INTEGER NOT NULL,
  engine_hours INTEGER NOT NULL,
  img_path TEXT NOT NULL,
  price INTEGER NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  featured BOOLEAN NOT NULL DEFAULT FALSE,
  date_posted TIMESTAMP NOT NULL
);
